language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.0
  - android-24
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
jdk:
- oraclejdk8
notifications:
  slack:
    secure: XRppapl5FCVPgl+1F+7tBdZ0ixnhO4kFCxbeUCFq+ZddgcM8OnQy+fZO5OqHILq4wJlLRjIje616Ym0ASlzi5nPlIPgdMXwjxsa2BOjEdWUITCMREt0+ZnW9Pe82GUyYHtOXRehceMrZJHS1YIB8/vsmU/j0O0J6MYgexD6MGj7L7yrRxdEaCAHAUJNPQHRHogkYwE7Y41PZ52bhMdFc9SzNHJkMbW/qtDw2l4+3he/N952YXqbeX78o6FipaxSVMZvwRkazkGDli8Qikvu1bO+UqkSEamP88tTkghqeW/PTt/+7BqMwNWdNLxn2qK/E6n90sSUaYskuhe1Uukmf9rI/zBtMOjVxpclegSPOE0WoVrpLaxRgkabbTVtykOu1V4Grng9CBkcFGBQ++JbIxyjzG73cxTBhisC8N4IiS1qirqRD1KjRO9UyV63qGcyIpRXW5dgO7a0g9t64/LJ8QIWuvUMbzzddk05myYcC9XWekH/U9nPtkaAxEzyLGVWgFAHmRjdcUx2xYgvPZSEohbUZdEsbWBPT11eTRhRMh3jVqAVfakZ6efp66jba05umAft5d6lW2EXzbspTnYuOy9+wudpIFK8vLJ67fIoq0s7VY/G0lZB3RE7IvylVvvX/aeauNtMB0AhCb1iSBwLPvplEDEHPM6QtqJzrld+0nbI=
